spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.130.41.196:3306/数据库课设?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: Haenu
    password: Haenu03170811.
  mail:
    host: smtp.163.com
    username: haenu0317@163.com
    password: HQDSCJGFXHVJJANU
    port: 465
    properties:
      from: haenu0317@163.com
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
  data:
    redis:
      database: 0
      host: 8.130.41.196
      port: 6379
      password: Haenu03170811

  # Mybatis开启驼峰映射
  mybatis:
    configuration:
      mapUnderscoreToCamelCase: true



